// WORLD CUP 2026 — MASTER DATA FILE
export interface Team { name:string; code:string; fifaRank:number; attackRating:number; defenseRating:number; avgCornersFor:number; avgCardsPerGame:number; }
export interface Fixture { id:string; group:string; mahtchday:number; homeTeam:string; awayTeam:string; date:string; time:string; venue:string; city:string; country:'USA'|'Mexico'|'Canada'; ukChannel:string; apiFixtureId?:number; status?:string; homeScore?:number; awayScore?:number; homeCorners?:number; awayCorners?:number; homeYellowCards?:number; awayYellowCards?:number; homeRedCards?:number; awayRedCards?:number; }
export const TEAMS: Record<string, Team> = {
  Argentina:  {name:'Argentina',   code:'ar',     fifaRank:1,  attackRating:2.20,defenseRating:0.62,avgCornersFor:5.8,avgCardsPerGame:1.5},
  France:     {name:'France',      code:'fr',     fifaRank:2,  attackRating:2.10,defenseRating:0.60,avgCornersFor:5.6,avgCardsPerGame:1.6},
  Spain:      {name:'Spain',       code:'es',     fifaRank:3,  attackRating:2.05,defenseRating:0.58,avgCornersFor:6.2,avgCardsPerGame:1.4},
  England:    {name:'England',     code:'gb-eng', fifaRank:4,  attackRating:1.95,defenseRating:0.65,avgCornersFor:5.9,avgCardsPerGame:1.3},
  Brazil:     {name:'Brazil',      code:'br',     fifaRank:5,  attackRating:2.00,defenseRating:0.63,avgCornersFor:5.5,avgCardsPerGame:1.7},
  Belgium:    {name:'Belgium',     code:'be',     fifaRank:6,  attackRating:1.85,defenseRating:0.68,avgCornersFor:5.4,avgCardsPerGame:1.5},
  Portugal:   {name:'Portugal',    code:'pt',     fifaRank:7,  attackRating:1.90,defenseRating:0.70,avgCornersFor:5.7,avgCardsPerGame:1.4},
  Netherlands:{name:'Netherlands', code:'nl',     fifaRank:8,  attackRating:1.88,defenseRating:0.72,avgCornersFor:5.5,avgCardsPerGame:1.5},
  Germany:    {name:'Germany',     code:'de',     fifaRank:9,  attackRating:1.85,defenseRating:0.70,avgCornersFor:5.6,avgCardsPerGame:1.4},
  Uruguay:    {name:'Uruguay',     code:'uy',     fifaRank:10, attackRating:1.65,defenseRating:0.75,avgCornersFor:4.8,avgCardsPerGame:1.8},
  Colombia:   {name:'Colombia',    code:'co',     fifaRank:11, attackRating:1.60,defenseRating:0.78,avgCornersFor:5.0,avgCardsPerGame:1.7},
  Croatia:    {name:'Croatia',     code:'hr',     fifaRank:14, attackRating:1.55,defenseRating:0.80,avgCornersFor:4.9,avgCardsPerGame:1.6},
  USA:        {name:'United States',code:'us',    fifaRank:15, attackRating:1.50,defenseRating:0.82,avgCornersFor:5.1,avgCardsPerGame:1.5},
  Mexico:     {name:'Mexico',      code:'mx',     fifaRank:16, attackRating:1.48,defenseRating:0.83,avgCornersFor:5.2,avgCardsPerGame:1.9},
  Morocco:    {name:'Morocco',     code:'ma',     fifaRank:14, attackRating:1.45,defenseRating:0.76,avgCornersFor:4.7,avgCardsPerGame:1.8},
  Ecuador:    {name:'Ecuador',     code:'ec',     fifaRank:17, attackRating:1.40,defenseRating:0.85,avgCornersFor:4.6,avgCardsPerGame:1.7},
  Japan:      {name:'Japan',       code:'jp',     fifaRank:18, attackRating:1.42,defenseRating:0.84,avgCornersFor:5.3,avgCardsPerGame:1.2},
  Senegal:    {name:'Senegal',     code:'sn',     fifaRank:19, attackRating:1.38,defenseRating:0.86,avgCornersFor:4.5,avgCardsPerGame:1.8},
  Switzerland:{name:'Switzerland', code:'ch',     fifaRank:20, attackRating:1.35,defenseRating:0.85,avgCornersFor:5.0,avgCardsPerGame:1.4},
  Iran:       {name:'Iran',        code:'ir',     fifaRank:21, attackRating:1.20,defenseRating:0.95,avgCornersFor:4.5,avgCardsPerGame:2.0},
  'South Korea':{name:'South Korea',code:'kr',   fifaRank:22, attackRating:1.30,defenseRating:0.90,avgCornersFor:5.0,avgCardsPerGame:1.4},
  Austria:    {name:'Austria',     code:'at',     fifaRank:23, attackRating:1.30,defenseRating:0.90,avgCornersFor:5.1,avgCardsPerGame:1.5},
  Australia:  {name:'Australia',   code:'au',     fifaRank:24, attackRating:1.28,defenseRating:0.92,avgCornersFor:4.8,avgCardsPerGame:1.4},
  Norway:     {name:'Norway',      code:'no',     fifaRank:25, attackRating:1.32,defenseRating:0.91,avgCornersFor:4.9,avgCardsPerGame:1.5},
  Sweden:     {name:'Sweden',      code:'se',     fifaRank:27, attackRating:1.25,defenseRating:0.93,avgCornersFor:4.7,avgCardsPerGame:1.4},
  "Cote d'Ivoire":{name:"Cote d'Ivoire",code:'ci',fifaRank:28,attackRating:1.28,defenseRating:0.92,avgCornersFor:4.6,avgCardsPerGame:1.8},
  Turkey:     {name:'Turkiye',     code:'tr',     fifaRank:29, attackRating:1.30,defenseRating:0.93,avgCornersFor:5.0,avgCardsPerGame:1.9},
  Ghana:      {name:'Ghana',       code:'gh',     fifaRank:30, attackRating:1.22,defenseRating:0.95,avgCornersFor:4.5,avgCardsPerGame:1.7},
  Tunisia:    {name:'Tunisia',     code:'tn',     fifaRank:31, attackRating:1.18,defenseRating:0.96,avgCornersFor:4.4,avgCardsPerGame:1.8},
  Czechia:    {name:'Czechia',     code:'cz',     fifaRank:33, attackRating:1.20,defenseRating:0.95,avgCornersFor:4.9,avgCardsPerGame:1.5},
  Algeria:    {name:'Algeria',     code:'dz',     fifaRank:35, attackRating:1.18,defenseRating:0.98,avgCornersFor:4.3,avgCardsPerGame:1.9},
  Paraguay:   {name:'Paraguay',    code:'py',     fifaRank:37, attackRating:1.15,defenseRating:1.00,avgCornersFor:4.2,avgCardsPerGame:1.9},
